[build]
  publish = "Build"

[[headers]]
  for = "/Build/*.js.gz"
  [headers.values]
    Content-Type = "application/javascript"
    Content-Encoding = "gzip"

[[headers]]
  for = "/Build/*.data.gz"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Encoding = "gzip"

[[headers]]
  for = "/Build/*.wasm.gz"
  [headers.values]
    Content-Type = "application/wasm"
    Content-Encoding = "gzip"

[[headers]]
  for = "/Build/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/Build/*.json"
  [headers.values]
    Content-Type = "application/json"