[build]
  publish = "."

[[headers]]
  for = "/Build/*.gz"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "/Build/*.data.gz"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Encoding = "gzip"

[[headers]]
  for = "/Build/*.js.gz"
  [headers.values]
    Content-Type = "application/javascript"
    Content-Encoding = "gzip"

[[headers]]
  for = "/Build/*.wasm.gz"
  [headers.values]
    Content-Type = "application/wasm"
    Content-Encoding = "gzip"